# pull-request.yml

name: danernoodle-io-org-pom
on: pull_request
jobs:
  build:
    uses: dangernoodle-io/dangernoodle-io-repos/.github/workflows/dn-maven-pull-request.yml@main
    secrets: inherit
    